"""add sector to regulatory_categories

Revision ID: 10423e67cc42
Revises: d4e5f6g7h8i9
Create Date: 2026-03-06 10:12:50.154997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10423e67cc42'
down_revision: Union[str, None] = 'd4e5f6g7h8i9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column with a server default so existing rows are populated
    op.add_column(
        'regulatory_categories',
        sa.Column('sector', sa.String(length=50), nullable=False, server_default='alimentacion'),
    )
    # Drop the server default — application code supplies the value going forward
    op.alter_column('regulatory_categories', 'sector', server_default=None)
    op.create_index(
        op.f('ix_regulatory_categories_sector'), 'regulatory_categories', ['sector'], unique=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulatory_categories_sector'), table_name='regulatory_categories')
    op.drop_column('regulatory_categories', 'sector')
    # ### end Alembic commands ###
